/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#660075",
        "tertiary": "#ec63ff",
        "surface-container-high": "#141f38",
        "surface-variant": "#192540",
        "surface-tint": "#81ecff",
        "inverse-on-surface": "#4d556b",
        "error": "#ff716c",
        "error-dim": "#d7383b",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#6063ee",
        "on-surface": "#dee5ff",
        "primary-container": "#00e3fd",
        "primary-dim": "#00d4ec",
        "on-error-container": "#ffa8a3",
        "surface-container-highest": "#192540",
        "on-tertiary-container": "#19001e",
        "tertiary-container": "#de4bf4",
        "on-surface-variant": "#a3aac4",
        "on-background": "#dee5ff",
        "surface": "#060e20",
        "primary": "#81ecff",
        "on-primary": "#005762",
        "on-primary-fixed": "#003840",
        "on-secondary-fixed-variant": "#3a3ac8",
        "secondary-fixed": "#cdcdff",
        "on-tertiary-fixed": "#300038",
        "tertiary-fixed": "#f487ff",
        "outline": "#6d758c",
        "error-container": "#9f0519",
        "outline-variant": "#40485d",
        "primary-fixed-dim": "#00d4ec",
        "background": "#060e20",
        "secondary-container": "#2f2ebe",
        "inverse-surface": "#faf8ff",
        "on-error": "#490006",
        "primary-fixed": "#00e3fd",
        "secondary-fixed-dim": "#bdbeff",
        "tertiary-fixed-dim": "#ef6eff",
        "inverse-primary": "#006976",
        "on-secondary-fixed": "#160bae",
        "secondary": "#9093ff",
        "on-primary-container": "#004d57",
        "tertiary-dim": "#ec63ff",
        "on-secondary-container": "#ccccff",
        "on-primary-fixed-variant": "#005762",
        "surface-dim": "#060e20",
        "surface-bright": "#1f2b49",
        "on-tertiary": "#3d0047",
        "on-secondary": "#080079",
        "surface-container-low": "#091328",
        "surface-container": "#0f1930",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
